#!/usr/bin/env python3
"""Build the clawmain agent library from catalog/*.toml.

Generates, for every department file in catalog/:
  plugins/<slug>/.claude-plugin/plugin.json
  plugins/<slug>/agents/<agent>.md        (loop contract from catalog/_harness.md)
  plugins/<slug>/README.md                (agent table + department graph)
and repo-wide:
  .claude-plugin/marketplace.json         (department entries; other entries kept)
  docs/catalog.md, docs/graph.md, docs/other-marketplaces.md
  plugins/groundwork/skills/groundwork/references/agent-catalog.md

Usage:
  python tools/build.py           write generated files
  python tools/build.py --check   exit 1 if any generated file is stale or the catalog is invalid
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog"
REPO_URL = "https://github.com/vishnu-77/clawmain.git"
MARKETPLACE = "clawmain"
AUTHOR = {"name": "vishnu-77", "url": "https://github.com/vishnu-77"}

MODELS = {"haiku", "sonnet", "opus", "inherit"}
STAGES = ["plan", "act", "verify", "reflect"]
TOOLS = {"Read", "Grep", "Glob", "Bash", "Edit", "Write", "WebFetch", "WebSearch", "NotebookEdit"}
WRITE_TOOLS = {"Edit", "Write", "NotebookEdit"}
MODES = {"read-only", "writes"}
COLORS = {"red", "blue", "green", "yellow", "purple", "orange", "pink", "cyan"}
NAME_RE = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*$")
DEFAULT_BUDGET = {"max_iterations": 4, "max_tokens": 40000}
GENERATED_NOTE = "<!-- Generated by tools/build.py from catalog/{src}. Edit the catalog, not this file. -->"


class CatalogError(Exception):
    pass


# ---------------------------------------------------------------- load + validate

def load_departments() -> list[dict]:
    departments = []
    for path in sorted(CATALOG.glob("*.toml")):
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        dept = data.get("department") or {}
        dept["_src"] = path.name
        dept["agents"] = data.get("agents") or []
        departments.append(dept)
    return departments


def validate(departments: list[dict]) -> list[str]:
    errors: list[str] = []
    names: dict[str, str] = {}
    slugs: set[str] = set()

    for dept in departments:
        src = dept["_src"]
        for key in ("slug", "title", "summary", "recommend_when", "color"):
            if not dept.get(key):
                errors.append(f"{src}: department.{key} is required")
        slug = dept.get("slug", "")
        if slug and not NAME_RE.match(slug):
            errors.append(f"{src}: slug '{slug}' must be kebab-case")
        if slug in slugs or slug == "groundwork":
            errors.append(f"{src}: duplicate or reserved slug '{slug}'")
        slugs.add(slug)
        if dept.get("color") and dept["color"] not in COLORS:
            errors.append(f"{src}: color must be one of {sorted(COLORS)}")
        if not dept["agents"]:
            errors.append(f"{src}: no agents")

        for agent in dept["agents"]:
            name = agent.get("name", "")
            where = f"{src}:{name or '?'}"
            if not NAME_RE.match(name):
                errors.append(f"{where}: name must be kebab-case")
            if name in names:
                errors.append(f"{where}: duplicate agent name (also in {names[name]})")
            names[name] = src
            for key in ("description", "why", "mission", "model", "mode", "loop_stage"):
                if not agent.get(key):
                    errors.append(f"{where}: {key} is required")
            desc = agent.get("description", "")
            if desc and "Use when" not in desc:
                errors.append(f"{where}: description must include 'Use when' trigger phrasing")
            if len(desc) > 400:
                errors.append(f"{where}: description over 400 chars (loaded every session)")
            if agent.get("why") and not 2 <= len(agent["why"].split()) <= 3:
                errors.append(f"{where}: why must be 2-3 words")
            if agent.get("model") and agent["model"] not in MODELS:
                errors.append(f"{where}: model must be one of {sorted(MODELS)}")
            if agent.get("loop_stage") and agent["loop_stage"] not in STAGES:
                errors.append(f"{where}: loop_stage must be one of {STAGES}")
            if agent.get("mode") and agent["mode"] not in MODES:
                errors.append(f"{where}: mode must be one of {sorted(MODES)}")
            tools = agent.get("tools") or []
            if not tools:
                errors.append(f"{where}: tools is required (least privilege)")
            bad = set(tools) - TOOLS
            if bad:
                errors.append(f"{where}: unknown tools {sorted(bad)}")
            if agent.get("mode") == "read-only" and WRITE_TOOLS & set(tools):
                errors.append(f"{where}: read-only agent must not have {sorted(WRITE_TOOLS & set(tools))}")
            if agent.get("mode") == "writes" and not WRITE_TOOLS & set(tools):
                errors.append(f"{where}: mode 'writes' but no write tool")
            for key, lo, hi in (("steps", 3, 8), ("outputs", 1, 8), ("guardrails", 1, 6)):
                count = len(agent.get(key) or [])
                if not lo <= count <= hi:
                    errors.append(f"{where}: {key} needs {lo}-{hi} items (has {count})")
            budget = agent.get("budget") or {}
            if set(budget) - set(DEFAULT_BUDGET):
                errors.append(f"{where}: budget keys must be {sorted(DEFAULT_BUDGET)}")

    for dept in departments:
        for agent in dept["agents"]:
            for handoff in agent.get("handoffs") or []:
                target = handoff.get("to")
                if target not in names:
                    errors.append(f"{dept['_src']}:{agent.get('name')}: handoff to unknown agent '{target}'")
                elif target == agent.get("name"):
                    errors.append(f"{dept['_src']}:{agent.get('name')}: handoff to itself")
                if not handoff.get("when"):
                    errors.append(f"{dept['_src']}:{agent.get('name')}: handoff to '{target}' needs 'when'")
    return errors


# ---------------------------------------------------------------- render

def dept_version(dept: dict) -> str:
    return dept.get("version", "0.1.0")


def title_of(name: str) -> str:
    return name.replace("-", " ").title().replace("Llm", "LLM").replace("Api", "API").replace("Pii", "PII")


def render_agent(dept: dict, agent: dict, harness: str, owner: dict[str, str]) -> str:
    budget = {**DEFAULT_BUDGET, **(agent.get("budget") or {})}
    lines = [
        "---",
        f"name: {agent['name']}",
        f"description: {json.dumps(agent['description'], ensure_ascii=False)}",
        f"tools: {', '.join(agent['tools'])}",
        f"model: {agent['model']}",
        f"color: {agent.get('color', dept['color'])}",
        "---",
        "",
        GENERATED_NOTE.format(src=dept["_src"]),
        "",
        f"# {title_of(agent['name'])}",
        "",
        f"**Department:** {dept['title']} · **Loop stage:** {agent['loop_stage']} · "
        f"**Mode:** {agent['mode']} · **Why:** {agent['why']}",
        "",
        agent["mission"].strip(),
        "",
        "## Steps",
        "",
    ]
    lines += [f"{i}. {step}" for i, step in enumerate(agent["steps"], 1)]
    lines += ["", "## Output", ""] + [f"- {item}" for item in agent["outputs"]]
    lines += ["", "## Guardrails", ""] + [f"- {item}" for item in agent["guardrails"]]
    if agent["mode"] == "read-only":
        bash = " Bash is for inspection and running checks only." if "Bash" in agent["tools"] else ""
        lines.append(f"- Read-only: do not modify files.{bash}")
    handoffs = agent.get("handoffs") or []
    if handoffs:
        lines += ["", "## Handoffs", ""]
        for handoff in handoffs:
            plugin = owner[handoff["to"]]
            ref = handoff["to"] if plugin == dept["slug"] else f"{handoff['to']} ({plugin} plugin)"
            lines.append(f"- **{ref}**: {handoff['when']}")
    lines += ["", harness.format(**budget).strip(), ""]
    return "\n".join(lines)


def mermaid_id(name: str) -> str:
    return name.replace("-", "_")


def render_dept_graph(dept: dict, owner: dict[str, str]) -> list[str]:
    lines = ["```mermaid", "flowchart LR"]
    for stage in STAGES:
        members = [a for a in dept["agents"] if a["loop_stage"] == stage]
        if members:
            lines.append(f"  subgraph {stage.upper()}[{stage}]")
            lines += [f"    {mermaid_id(a['name'])}[{a['name']}]" for a in members]
            lines.append("  end")
    external = set()
    for agent in dept["agents"]:
        for handoff in agent.get("handoffs") or []:
            if owner[handoff["to"]] != dept["slug"]:
                external.add(handoff["to"])
            lines.append(f"  {mermaid_id(agent['name'])} --> {mermaid_id(handoff['to'])}")
    for name in sorted(external):
        lines.append(f"  {mermaid_id(name)}([{name} · {owner[name]}])")
    lines.append("```")
    return lines


def render_dept_readme(dept: dict, owner: dict[str, str]) -> str:
    lines = [
        GENERATED_NOTE.format(src=dept["_src"]),
        "",
        f"# {dept['title']}",
        "",
        dept["summary"].strip(),
        "",
        "```",
        f"/plugin marketplace add vishnu-77/{MARKETPLACE}",
        f"/plugin install {dept['slug']}@{MARKETPLACE}",
        "```",
        "",
        f"Every agent follows the shared [loop contract](../../docs/loop-harness.md): plan, act, "
        "verify, reflect, with budgets, stop conditions and an evidence-backed report.",
        "",
        "| Agent | Stage | Mode | Model | Why | Use when |",
        "|---|---|---|---|---|---|",
    ]
    for agent in dept["agents"]:
        use_when = agent["description"].split("Use when", 1)[1].strip().rstrip(".")
        lines.append(
            f"| `{agent['name']}` | {agent['loop_stage']} | {agent['mode']} | {agent['model']} "
            f"| {agent['why']} | {use_when} |"
        )
    lines += ["", "## Handoff graph", ""] + render_dept_graph(dept, owner) + [""]
    return "\n".join(lines)


def render_plugin_json(dept: dict) -> str:
    data = {
        "name": dept["slug"],
        "displayName": dept["title"],
        "version": dept_version(dept),
        "description": dept["summary"].strip().split("\n")[0],
        "author": AUTHOR,
        "homepage": f"https://github.com/vishnu-77/{MARKETPLACE}/tree/main/plugins/{dept['slug']}",
        "repository": f"https://github.com/vishnu-77/{MARKETPLACE}",
        "license": "MIT",
        "keywords": ["agents", "clawmain", dept["slug"]],
    }
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def render_marketplace(departments: list[dict]) -> str:
    path = ROOT / ".claude-plugin" / "marketplace.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    generated = {d["slug"] for d in departments}
    kept = [p for p in data.get("plugins", []) if p["name"] not in generated]
    entries = [
        {
            "name": d["slug"],
            "source": f"./plugins/{d['slug']}",
            "description": d["summary"].strip().split("\n")[0],
            "version": dept_version(d),
            "category": "agents",
            "keywords": ["agents", d["slug"]],
        }
        for d in departments
    ]
    data["plugins"] = kept + entries
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def render_catalog_doc(departments: list[dict]) -> str:
    total = sum(len(d["agents"]) for d in departments)
    lines = [
        "<!-- Generated by tools/build.py. Edit catalog/*.toml, not this file. -->",
        "",
        "# Agent catalog",
        "",
        f"{total} agents in {len(departments)} department plugins. Install a department with "
        f"`/plugin install <department>@{MARKETPLACE}`.",
        "",
    ]
    for dept in departments:
        lines += [f"## {dept['title']} (`{dept['slug']}`, {len(dept['agents'])} agents)", "",
                  dept["summary"].strip(), "", "| Agent | Stage | Why | Mission |", "|---|---|---|---|"]
        for agent in dept["agents"]:
            mission = agent["mission"].strip().split("\n")[0]
            lines.append(f"| `{agent['name']}` | {agent['loop_stage']} | {agent['why']} | {mission} |")
        lines.append("")
    return "\n".join(lines)


def render_graph_doc(departments: list[dict], owner: dict[str, str]) -> str:
    edges: dict[tuple[str, str], int] = {}
    for dept in departments:
        for agent in dept["agents"]:
            for handoff in agent.get("handoffs") or []:
                pair = (dept["slug"], owner[handoff["to"]])
                if pair[0] != pair[1]:
                    edges[pair] = edges.get(pair, 0) + 1
    lines = [
        "<!-- Generated by tools/build.py. Edit catalog/*.toml, not this file. -->",
        "",
        "# Agent graph",
        "",
        "## The loop every agent runs",
        "",
        "```mermaid",
        "flowchart LR",
        "  P[Plan] --> A[Act] --> V[Verify] --> R[Reflect]",
        "  R -->|progress, budget left| P",
        "  R -->|criteria met with evidence| D([Report])",
        "  V -->|same failure twice| S([Stop: report])",
        "  A -->|irreversible action| G([Stop: ask user])",
        "  D -->|handoff| H{{Main session routes to next agent}}",
        "```",
        "",
        "## Departments and cross-department handoffs",
        "",
        "Edge labels count handoffs from agents in one department to agents in another.",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for dept in departments:
        lines.append(f"  {mermaid_id(dept['slug'])}[{dept['title']} · {len(dept['agents'])}]")
    for (src, dst), count in sorted(edges.items()):
        lines.append(f"  {mermaid_id(src)} -->|{count}| {mermaid_id(dst)}")
    lines += ["```", "", "## Per-department handoff graphs", ""]
    for dept in departments:
        lines += [f"### {dept['title']}", ""] + render_dept_graph(dept, owner) + [""]
    return "\n".join(lines)


def render_other_marketplaces(departments: list[dict]) -> str:
    lines = [
        "<!-- Generated by tools/build.py. -->",
        "",
        "# Use clawmain plugins from any marketplace",
        "",
        f"The simplest route: `/plugin marketplace add vishnu-77/{MARKETPLACE}`.",
        "",
        "To list a clawmain plugin inside **your own** marketplace, add an entry with a "
        "`git-subdir` source. Claude Code sparse-clones only that plugin's folder. Pin `ref` to a "
        "tag (or add `sha`) for reproducible installs.",
        "",
        "```json",
    ]
    example = [
        {
            "name": slug,
            "source": {"source": "git-subdir", "url": REPO_URL, "path": f"plugins/{slug}", "ref": "main"},
            "description": desc,
        }
        for slug, desc in [("groundwork", "Guided Claude Code setup with why-tag lessons.")]
        + [(d["slug"], d["summary"].strip().split("\n")[0]) for d in departments]
    ]
    lines += [json.dumps({"plugins": example}, indent=2, ensure_ascii=False), "```", ""]
    return "\n".join(lines)


def render_groundwork_catalog(departments: list[dict]) -> str:
    lines = [
        "<!-- Generated by tools/build.py. Edit catalog/*.toml, not this file. -->",
        "",
        "# clawmain agent departments",
        "",
        "Use this to recommend agent plugins at the end of `/groundwork` (init). Recommend at most 3 "
        "departments, matched to the repo profile and the user's answers. Give each a why-tag.",
        "",
        f"Install: `/plugin install <slug>@{MARKETPLACE}` (after `/plugin marketplace add vishnu-77/{MARKETPLACE}`).",
        "",
        "| Slug | Recommend when | Agents |",
        "|---|---|---|",
    ]
    for dept in departments:
        agents = ", ".join(a["name"] for a in dept["agents"])
        lines.append(f"| `{dept['slug']}` | {dept['recommend_when'].strip()} | {agents} |")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- main

def build() -> dict[Path, str]:
    departments = load_departments()
    errors = validate(departments)
    if errors:
        raise CatalogError("\n".join(errors))
    harness = (CATALOG / "_harness.md").read_text(encoding="utf-8")
    owner = {a["name"]: d["slug"] for d in departments for a in d["agents"]}

    outputs: dict[Path, str] = {}
    for dept in departments:
        base = ROOT / "plugins" / dept["slug"]
        outputs[base / ".claude-plugin" / "plugin.json"] = render_plugin_json(dept)
        outputs[base / "README.md"] = render_dept_readme(dept, owner)
        for agent in dept["agents"]:
            outputs[base / "agents" / f"{agent['name']}.md"] = render_agent(dept, agent, harness, owner)
    outputs[ROOT / ".claude-plugin" / "marketplace.json"] = render_marketplace(departments)
    outputs[ROOT / "docs" / "catalog.md"] = render_catalog_doc(departments)
    outputs[ROOT / "docs" / "graph.md"] = render_graph_doc(departments, owner)
    outputs[ROOT / "docs" / "other-marketplaces.md"] = render_other_marketplaces(departments)
    outputs[ROOT / "plugins" / "groundwork" / "skills" / "groundwork" / "references" / "agent-catalog.md"] = (
        render_groundwork_catalog(departments)
    )
    return outputs


def stale_agent_files(outputs: dict[Path, str]) -> list[Path]:
    """Agent files on disk in generated plugins that the catalog no longer defines."""
    stale = []
    for plugin_dir in {p.parent.parent for p in outputs if p.parent.name == "agents"}:
        for path in (plugin_dir / "agents").glob("*.md"):
            if path not in outputs:
                stale.append(path)
    return stale


def main(argv: list[str]) -> int:
    check = "--check" in argv
    try:
        outputs = build()
    except CatalogError as exc:
        print(f"catalog invalid:\n{exc}", file=sys.stderr)
        return 1
    changed = [p for p, text in outputs.items()
               if not p.exists() or p.read_text(encoding="utf-8") != text]
    stale = stale_agent_files(outputs)
    if check:
        for path in changed + stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        if changed or stale:
            print("run: python tools/build.py", file=sys.stderr)
            return 1
        print(f"ok: {len(outputs)} generated files up to date")
        return 0
    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(outputs[path], encoding="utf-8", newline="\n")
    for path in stale:
        path.unlink()
    agents = sum(1 for p in outputs if p.parent.name == "agents")
    print(f"built {agents} agents; wrote {len(changed)} files, removed {len(stale)} stale")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
